### ISSUE TITLE
Add styles

### ISSUE THREAD

**Issue by jessicasalmon** [FAC10/week-6-jajascript#42]

**Comment by sohilpandya** [comment]
@bo-bok Nice CSS! 😉 

Although something worth thinking about is the usage of REM and EM. It's not good practice to use both REM and EM for the same piece of CSS 
```css
.companies-form-submit {
  display: block;
  margin: 0 0 0 auto;
  padding: 0.5em 0.75em;
  font-size: 1.2rem;
  background: none;
  border: 2px solid #4FB286;
  transition: all 0.2s;
  color: #6B6D76;
}
```

What I'd suggest is that you define a top level font so instead of https://github.com/FAC10/week-6-jajascript/blob/master/public/styles.css#L28 setting this to em, you'd set this top level to 14px/16px and then everywhere else in your CSS you'd use REM to refer to this font-size. That way you know exactly how sizes will behave. 

Personally, I'd go down the route of using 16px as it works out to nice round numbers. (i.e. using 32px font size would be 2rem if body font-size is set to 16px, but it'd be 2.285 if you were using 14px)

I'm not sure If I've already made a similar issue in an earlier week, but thought it was worth writing up again.

✌️
